### ISSUE TITLE
feature request: implement count()

### ISSUE THREAD

**Issue by MatthieuStigler** [hadley/dtplyr#59] opened 2018-09-20 22:25 UTC
Hi 

It seems `count()` is not working straight out of the box on data.tables? It throws an error for now: *Error: `:=` can only be used within a quasiquoted argument*

``` r
library(tidyverse)
library(data.table)
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
#> The following object is masked from 'package:purrr':
#> 
#>     transpose
library(dtplyr)


as.data.table(iris) %>%
  count(Species)
#> Error: `:=` can only be used within a quasiquoted argument
```

**Comment by hadley** [comment] 2019-05-25 13:48
Current reprex:

``` r
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

iris %>%  
  as.data.table() %>%
  count(Species)
#> Error in data.table::is.data.table(data): invalid subscript type 'list'
```

<sup>Created on 2019-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment] 2019-06-13 16:05
Duplicate of #33.

**Closed by hadley** 2019-06-13 16:05 UTC
Labels: bug, dplyr-compat 💞
