### ISSUE TITLE
Mutate returns nothing

### ISSUE THREAD

**Issue by hadley** [hadley/dtplyr#11] opened 2016-03-08 15:04 UTC
Moved from https://github.com/hadley/dplyr/issues/1431, by @dbuijs 

```R
library(dplyr)
library(data.table)

mutate(data.table(x = 1), y = 2)
```

**Comment by mattmalin** [comment] 2016-03-10 15:40
The issue is that the first show of the returned data.table displays nothing, not that the call *returns* nothing. Calling `.Last.value` after the example would display the data.table as expected.

In this case, running `mutate(data.table(x=1), y = 2)` will display nothing, but the return if assigned does include the correct data table with y=2 included. 

e.g. `print(mutate(data.table(x = 1), y = 2))` displays correctly, as will assigning it and referencing elements from the return (e.g. `mutate(data.table(x = 1), y = 2)[["y"]]` returns and shows 2).

**Comment by krlmlr** [comment] 2016-07-01 10:38
Root cause: After *some* operations, a data table doesn't auto-print itself on the *next* invocation of print().

When using dplyr, it's not transparent anymore if the underlying operations mute the auto-print. We should therefore always return `data[]` instead of `data` to [guarantee visible output](https://github.com/Rdatatable/data.table/blob/41e2a7f35e11b74f036bccc2bf5352f566d49955/R/data.table.R#L40).

**Closed** 2016-07-02 17:31 UTC

**Comment by krlmlr** [comment] 2016-07-02 17:32
Fixed now. Unfortunately, this seems to be difficult to test automatically with the CRAN version: data.table will always print from within a function.
